version: '3.8'

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["web"]
    expose:
      - 8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
      
  db:
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
